@startuml

class FlujoDeTrabajo{

 - private final int id;
 - private  String nombre;
 - private final List<IRecomendacion> recomendaciones;
 - private final List<IRetraso> retrasos;
 + public vois mostrarRecomendaciones();
 + public void mostrarRetrasos();

}



@enduml